import './globals.css'
import { MediumProvider } from '@/context/Mediumcontext'
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <MediumProvider>{children}</MediumProvider>
      </body>
    </html>
  )
}
